on:
  push:
    tags:
      - '[0-9]+.*'

name: Release

permissions: {}

jobs:
  build:
    uses: ./.github/workflows/test.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
      - id: download_artifact
        name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: jar

      - id: create_release
        name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ needs.build.outputs.project_name }} ${{ needs.build.outputs.project_version }}
          files: ${{ needs.build.outputs.artifact_id }}-${{ needs.build.outputs.project_version }}.jar
          fail_on_unmatched_files: true
          generate_release_notes: true
